version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/open-friendly-net-detection-client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
